
batch_size : 32
epoch : 100
lr : 0.01
lr_gamma : 0.83
split_ratio : 0.8
random_seed : [2, 3, 5, 7, 11, 13, 17, 19, 23, 998244353]
data_path : './data/ttc-streetcar-delay-data-2020-with-stations.xlsx'
weight_decay : 0.001

node_num : 343

k_neighbors : 60
time_interval_minutes : 480
time_limit : 25

self_enhance:
  spatial_adj_lmb : 2
  temporal_adj_lmb : 2
  neighbor_adj_lmb : 2

raw_cols:
  - 'Day'
  - 'Date'
  - 'Time'
  - 'Route'
  - 'Incident'
  - 'Delay'
  - 'Station ID'



graph_feature_cols:
  # - 'Station ID'
  - 'Route'
  - 'Incident'
  - 'Time'
  - 'Day'
  - 'Month'